openapi: 3.0.2
info:
  title: Payments Multiplexer
  version: '0.1'
  description: >-
    An API to perform a disbursements through various payment execution systems
  license:
    name: TBD
    url: TBD
servers:
  - url: /
paths:
  /health:
    get:
      operationId: HealthGet
      summary: Health check endpoint
      description: >-
        The HTTP request GET /health is used to return the current status of the
        API.
      tags:
        - health
      responses:
        '200':
          $ref: '#/components/responses/200'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
        '406':
          $ref: '#/components/responses/406'
        '501':
          $ref: '#/components/responses/501'
        '503':
          $ref: '#/components/responses/503'

  /disbursementCheck:
    post:
      operationId: DisbursementCheck
      description: >-
        This request is used check the feasibility of a disbursement.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisbursementRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisbursementCheckResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
        '406':
          $ref: '#/components/responses/406'
        '501':
          $ref: '#/components/responses/501'
        '503':
          $ref: '#/components/responses/503'

  /disbursement:
    post:
      operationId: Disbursement
      description: >-
        This request is used initiate a disbursement.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisbursementRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisbursementResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
        '406':
          $ref: '#/components/responses/406'
        '501':
          $ref: '#/components/responses/501'
        '503':
          $ref: '#/components/responses/503'
  /disbursement/{disbursementId}:
    get:
      operationId: GetDisbursement
      description: >-
        This request is used get the status of a disbursement.
      parameters:
      - name: disbursementId
        in: path
        description: disbursementId
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisbursementResponse'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '405':
          $ref: '#/components/responses/405'
        '406':
          $ref: '#/components/responses/406'
        '501':
          $ref: '#/components/responses/501'
        '503':
          $ref: '#/components/responses/503'

components:
  responses:
    '200':
      description: OK
    '400':
      description: Bad Request
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '404':
      description: Not Found
    '405':
      description: Method Not Allowed
    '406':
      description: Not Acceptable
    '501':
      description: Not Implemented
    '503':
      description: Service Unavailable


  headers:
    Content-Length:
      required: false
      schema:
        type: integer
      description: >-
        The `Content-Length` header field indicates the anticipated size of the
        payload body. Only sent if there is a body.


        **Note:** The API supports a maximum size of 5242880 bytes (5
        Megabytes).
    Content-Type:
      schema:
        type: string
      required: true
      description: >-
        The `Content-Type` header indicates the specific version of the API used
        to send the payload body.
  schemas:
    DisbursementRequest:
      title: DisbursementRequest
      type: object
      required:
        - disbursementId
        - payeeList
      properties:
        disbursementId: 
          type: string
          example: f2957f7a-34c3-11ed-a261-0242ac120002
        note: 
          type: string
          example: PENSION
        payeeList:
          type: array
          minItems: 1
          maxItems: 1000
          items:
            $ref: '#/components/schemas/IndividualPayee'
      description: Data model for Disbursement Request
      example: |-
        {
          "disbursementId": "f2957f7a-34c3-11ed-a261-0242ac120002",
          "note": "PENSION",
          "payeeList": [
            {
              "payeeIdType": "NATIONAL_ID",
              "payeeIdValue": "345678912",
              "amount": 100,
              "currency": "INR"
            },
            {
              "payeeIdType": "NATIONAL_ID",
              "payeeIdValue": "562591356",
              "amount": 100,
              "currency": "INR"
            }
          ]
        }

    DisbursementResponse:
      title: DisbursementResponse
      type: object
      required:
        - disbursementId
        - payeeList
      properties:
        disbursementId: 
          type: string
          example: f2957f7a-34c3-11ed-a261-0242ac120002
        results:
          type: array
          minItems: 1
          maxItems: 1000
          items:
            $ref: '#/components/schemas/IndividualPayeeResult'
      description: Data model for Disbursement Response
  
    DisbursementCheckResponse:
      title: DisbursementResponse
      type: object
      required:
        - disbursementId
        - payeeList
      properties:
        disbursementId: 
          type: string
          example: f2957f7a-34c3-11ed-a261-0242ac120002
        payeeResults:
          type: array
          minItems: 1
          maxItems: 1000
          items:
            $ref: '#/components/schemas/IndividualPayeeCheckResult'
      description: Data model for Disbursement Check Response

    IndividualPayee:
      title: IndividualPayee
      type: object
      description: Data model for the complex type IndividualPayee.
      properties:
        payeeIdType: 
          type: string
          example: NATIONAL_ID
        payeeIdValue: 
          type: string
          example: 5000-0000-1234
        amount: 
          type: string
          example: 100
        currency: 
          type: string
          example: INR
      required:
        - payeeIdType
        - payeeIdValue
        - amount
        - currency
    IndividualPayeeResult:
      title: IndividualPayeeResult
      type: object
      description: Data model for the complex type IndividualPayeeResult.
      allOf:
        - $ref: '#/components/schemas/IndividualPayee'
        - type: object
          properties:
            isSuccess: 
              type: boolean
              example: true
            paymentExecutionSystem:
              type: string
              description: Type of payment execution system.
              example: MOJALOOP
            paymentExecutionSystemInfo:
              type: object
              description: Payment execution system specific information of payee for making a payment.
              example:
                payerDfspId: GovtBank
                payerIdType: ACCOUNT_ID
                payerIdValue: GOV/00001234
                payeeIdType: MSISDN
                payeeIdValue: 9876543210
            timestamp:
              type: string
              example: 2012-04-23T18:25:43.511Z
            result: 
              type: object
              description: Payment execution system specific result.
            errors:
              type: array
              items:
                type: string
                description: error description.
      required:
        - payeeIdType
        - payeeIdValue
        - amount
        - currency
    IndividualPayeeCheckResult:
      title: IndividualPayeeResult
      type: object
      description: Data model for the complex type IndividualPayeeResult.
      allOf:
        - $ref: '#/components/schemas/IndividualPayee'
        - type: object
          properties:
            isPayable: 
              type: boolean
              example: true
            paymentExecutionSystem:
              type: string
              description: Type of payment execution system.
              example: MOJALOOP
            paymentExecutionSystemInfo:
              type: object
              description: Payment execution system specific information of payee for making a payment.
              example:
                payerDfspId: GovtBank
                payerIdType: ACCOUNT_ID
                payerIdValue: GOV/00001234
                payeeIdType: MSISDN
                payeeIdValue: 9876543210
            timestamp:
              type: string
              example: 2012-04-23T18:25:43.511Z
            result: 
              type: object
              description: Payment execution system specific result.
            errors:
              type: array
              items:
                type: string
                description: error description.

      required:
        - payeeIdType
        - payeeIdValue
        - amount
        - currency
